services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: